### ISSUE TITLE
nested documents

### ISSUE THREAD

**Issue by arademaker** [franzinc/solr#4]
Can we use this library to add nested documents into SOLR?

http://www.slideshare.net/MarkHarwood/proposal-for-nested-document-support-in-lucene

**Comment by mbancroft** [comment]
Nested documents are not currently supported. The document specification
assumes that each subelement of the doc passed into solr-add is a (field .
value) pair. We'd need to extend this, maybe to allow sublists of the form
((field . value) ...). I'll file a feature request and see if this approach
is feasible.

-Mikel


On Wed, May 13, 2015 at 10:48 AM, Alexandre Rademaker <
notifications@github.com> wrote:

> Can we use this library to add nested documents into SOLR?
>
>
> http://www.slideshare.net/MarkHarwood/proposal-for-nested-document-support-in-lucene
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/franzinc/solr/issues/4>.
>



-- 
"From thirty feet away she looked like a lot of class. From ten feet away
she looked like something made up to be seen from thirty feet away."
-P. Marlowe

**Comment by mbancroft** [comment]
Nested document support has been added by [9d37e91](https://github.com/franzinc/solr/commit/9d37e91bc1ea99c35515c796903e35995983b1b2). Example:

```
(solr-add *solr* '((:id . 10)
                          (:pretext_t . "In")
                          ((:id . 11) (:subtext_t . "A leaf falls"))
                          (:context_t . "Parent")
                          (:subtext_t . "Loneliness"))
  :commit t)
```
