### ISSUE TITLE
doc-node->alist missing :double ECASE

### ISSUE THREAD

**Issue by fcbr** [franzinc/solr#5]
Hi, the doc-node->alist should have a case for :double.  I just added another item to the :float entry and it worked for my case.  The change is pretty trivial, so I don't think it warrant a pull request.

**Comment by mbancroft** [comment]
Hello,

Agreed that this is a pretty trivial change, which I will make. I also
realize that I need to make sure that it's possible to add double's and
floats via solr-add. At the moment it looks like double-float _may_ work
depending on the size of the value and the setting of
*read-default-float-format*.

Thanks for pointing this out. I'll push a commit later today, I believe.


On Thu, Jul 9, 2015 at 3:50 PM, Fabricio Chalub <notifications@github.com>
wrote:

> Hi, the doc-node->alist should have a case for :double. I just added
> another item to the :float entry and it worked for my case. The change is
> pretty trivial, so I don't think it warrant a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/franzinc/solr/issues/5>.
>



-- 
"From thirty feet away she looked like a lot of class. From ten feet away
she looked like something made up to be seen from thirty feet away."
-P. Marlowe

**Comment by mbancroft** [comment]
Better support for doubles added in [9d37e91](https://github.com/franzinc/solr/commit/9d37e91bc1ea99c35515c796903e35995983b1b2).

Thanks for the report.
