### ISSUE TITLE
:double type not recognized

### ISSUE THREAD

**Issue by arademaker** [franzinc/solr#6]
```
$ git diff
diff --git a/solr.lisp b/solr.lisp
index 4e1fec6..bff336e 100644
--- a/solr.lisp
+++ b/solr.lisp
@@ -285,10 +285,10 @@ query by :rows parameter:
                  ((:str)      (car vals))
                  ((:arr :lis) (mapcar #'get-value vals))
                  ((:int :long) (parse-integer (car vals)))
-                 ((:float)    (let ((v (read-from-string (car vals))))
-                                (unless (realp v)
-                                  (error "Invalid float number:" (car vals)))
-                                v))
+                 ((:float :double)    (let ((v (read-from-string (car vals))))
+                                       (unless (realp v)
+                                         (error "Invalid float number:" (car vals)))
+                                       v))
                  ((:bool)     (not (equal (car vals) "false")))
                  ((:date)     (parse-iso8601 (car vals)))))))
     (mapcar (lambda (n) (cons (get-name n) (get-value n))) (cdr node))))
```

This changed solved my problem!

**Comment by mbancroft** [comment]
Hi Alexander,

Good to hear. Thanks for letting us know!

-Mikel


On Wed, Mar 30, 2016 at 4:34 PM, Alexandre Rademaker <
notifications@github.com> wrote:

> $ git diff
> diff --git a/solr.lisp b/solr.lisp
> index 4e1fec6..bff336e 100644
> --- a/solr.lisp
> +++ b/solr.lisp
> @@ -285,10 +285,10 @@ query by :rows parameter:
>                   ((:str)      (car vals))
>                   ((:arr :lis) (mapcar #'get-value vals))
>                   ((:int :long) (parse-integer (car vals)))
> -                 ((:float)    (let ((v (read-from-string (car vals))))
> -                                (unless (realp v)
> -                                  (error "Invalid float number:" (car vals)))
> -                                v))
> +                 ((:float :double)    (let ((v (read-from-string (car vals))))
> +                                       (unless (realp v)
> +                                         (error "Invalid float number:" (car vals)))
> +                                       v))
>                   ((:bool)     (not (equal (car vals) "false")))
>                   ((:date)     (parse-iso8601 (car vals)))))))
>      (mapcar (lambda (n) (cons (get-name n) (get-value n))) (cdr node))))
>
> This changed solved my problem!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/franzinc/solr/issues/6>
>



-- 
“What else can the young be? When you are on the bottom, you must organize
from the bottom up!”

**Comment by arademaker** [comment]
Hum.. Will it be considered to be added in the code? Do you prefer a pull request?

**Comment by mbancroft** [comment]
Sorry for the confusion. I may be confused myself, but I'm pretty sure an
equivalent change was added as part of commit 9d37e91. Do you not see this
if you pull the latest updates?

-Mikel

On Thu, Mar 31, 2016 at 1:12 PM, Alexandre Rademaker <
notifications@github.com> wrote:

> Hum.. Will it be considered to be added in the code? Do you prefer a pull
> request?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/franzinc/solr/issues/6#issuecomment-204106128>
>



-- 
“What else can the young be? When you are on the bottom, you must organize
from the bottom up!”

**Comment by arademaker** [comment]
Oh, now I understood. My mistake, sorry. Long time ago I made a clone of this repo on my GitHub account: 

https://github.com/arademaker/solr

If I remember right, it was for making a PR. My local repo is a clone of my own GitHub repo. That is why I didn't see the last updates.

**Comment by mbancroft** [comment]
Understood. I'm glad we were able to figure things out.

I may have forgotten to let you know about the commit back when we pushed
it to github, too. Our github repositories tend to be push-only as we don't
have a process for moving pull requests through our internal code review
process. As a result, it's a good idea to watch our repos for changes.

Anyways, happy hacking! Let us know if you run into any other issues.

-Mikel


On Thu, Mar 31, 2016 at 6:57 PM, Alexandre Rademaker <
notifications@github.com> wrote:

> Oh, now I understood. My mistake, sorry. Long time ago I made a clone of
> this repo on my GitHub account:
>
> https://github.com/arademaker/solr
>
> If I remember right, it was for making a PR. My local repo is a clone of
> my own GitHub repo. That is why I didn't see the last updates.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/franzinc/solr/issues/6#issuecomment-204206522>
>



-- 
“What else can the young be? When you are on the bottom, you must organize
from the bottom up!”
